CREATE TABLE FRIENDS(ID INTEGER,NAME TEXT,BIRTHDAY DATE);

INSERT INTO FRIENDS(ID,NAME,BIRTHDAY) VALUES(1, 'Ororo Munroe','1940-05-30');
INSERT INTO FRIENDS(ID,NAME,BIRTHDAY) VALUES(2, 'SAAI','2004-03-28');
INSERT INTO FRIENDS(ID,NAME,BIRTHDAY) VALUES(3, 'B KAVIN','2004-05-28');
SELECT * FROM FRIENDS;

UPDATE  FRIENDS SET NAME='STORM' WHERE ID=1 ;
SELECT * FROM FRIENDS;

-- --ALTER TO ADD A NEW COLUMN IN EXISTING TABLE
/* SK
*/
ALTER TABLE FRIENDS ADD COLUMN EMAIL TEXT;
SELECT * FROM FRIENDS;

UPDATE FRIENDS SET EMAIL='storm@codecademy.com' 
WHERE ID =1;
DELETE FROM FRIENDS WHERE ID=1;
SELECT * FROM FRIENDS;


